# Numpy - Slicing & Indexing of an array.

In [1]:
import numpy as np

###### Creating a 1 dimensional array

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Indexing a 2D array 

In [6]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
arr_2d[1]


array([20, 25, 30])

In [8]:
arr_2d[1][0]

20

In [9]:
arr_2d[1,0]

20

In [10]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [11]:
arr_2d[2]

array([35, 40, 45])

In [12]:
arr_2d[2,:]

array([35, 40, 45])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr_view = arr[0:6]

arr_view

array([0, 1, 2, 3, 4, 5])

In [17]:
arr_view[:]=99

arr_view

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])